-- PostgreSQL port of cog_framework_test.sql, asserted against by
-- src/Test/TestPostgreSql.php. Changing anything here means changing those
-- assertions too, the same way the MySQL fixture and TestDatabase are paired.
--
-- The table set, the column set and the index ordering deliberately match the
-- MySQL fixture, so the two adapters can be held to the same expectations.
-- Four things have no direct equivalent and were mapped by hand:
--
--   INT UNSIGNED AUTO_INCREMENT -> integer GENERATED BY DEFAULT AS IDENTITY
--                                  (PostgreSQL has no unsigned integer type)
--   TINYINT(1)                  -> boolean
--   DATETIME                    -> timestamp
--   TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
--                               -> timestamp plus a trigger. PostgreSQL has no
--                                  self-updating column type, and a trigger is
--                                  invisible to the catalog, so the generator
--                                  cannot recognise blog_post.modification_date
--                                  as an optimistic locking token the way it
--                                  does under MySQL.
--
-- Unlike the MySQL fixture this does not create the database - PostgreSQL
-- cannot drop the database it is connected to. Load it with:
--     createdb cog_framework_test
--     psql -d cog_framework_test -f src/Test/cog_framework_test_pg.sql

DROP TRIGGER IF EXISTS blog_post_touch ON blog_post;
DROP FUNCTION IF EXISTS touch_modification_date();
DROP TABLE IF EXISTS person_person_assn, person_profile, category, empty_type,
	priority_type, tag_obj_assn, tag, asset, blog_post, blog_type, obj, person CASCADE;

CREATE TABLE person (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(255) NOT NULL,
	email varchar(255) NOT NULL,
	email_verified boolean NOT NULL DEFAULT false,
	password varchar(255) NOT NULL,
	CONSTRAINT email UNIQUE (email)
);
CREATE INDEX name ON person (name);
CREATE INDEX email_verified ON person (email_verified);
COMMENT ON COLUMN person.email IS 'primary contact address';

CREATE TABLE obj (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	person_id integer NOT NULL,
	label varchar(255) NOT NULL,
	creation_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT obj_person_id FOREIGN KEY (person_id) REFERENCES person (id)
);
CREATE INDEX obj_person_id_idx ON obj (person_id);

CREATE TABLE blog_type (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(100) NOT NULL,
	CONSTRAINT blog_type_name UNIQUE (name)
);

CREATE TABLE blog_post (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	obj_id integer NOT NULL,
	type_id integer NOT NULL,
	author_id integer NOT NULL,
	title varchar(255) NOT NULL,
	body text,
	modification_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT blog_post_type_id FOREIGN KEY (type_id) REFERENCES blog_type (id),
	CONSTRAINT blog_post_obj_id FOREIGN KEY (obj_id) REFERENCES obj (id),
	CONSTRAINT blog_post_author_id FOREIGN KEY (author_id) REFERENCES person (id)
);
CREATE INDEX blog_post_author_id_idx ON blog_post (author_id);
CREATE INDEX blog_post_type_id_idx ON blog_post (type_id);
CREATE INDEX blog_post_obj_id_idx ON blog_post (obj_id);

-- MySQL's ON UPDATE CURRENT_TIMESTAMP has no PostgreSQL equivalent; the
-- optimistic-locking token has to be maintained by a trigger instead.
CREATE OR REPLACE FUNCTION touch_modification_date() RETURNS trigger AS $$
BEGIN
	NEW.modification_date = CURRENT_TIMESTAMP;
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER blog_post_touch BEFORE UPDATE ON blog_post
	FOR EACH ROW EXECUTE FUNCTION touch_modification_date();

CREATE TABLE asset (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	obj_id integer NOT NULL,
	filename varchar(255) NOT NULL,
	mime_type varchar(128) NOT NULL,
	size integer NOT NULL DEFAULT 0,
	CONSTRAINT asset_obj_id FOREIGN KEY (obj_id) REFERENCES obj (id)
);
CREATE INDEX asset_obj_id_idx ON asset (obj_id);

CREATE TABLE tag (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(200) NOT NULL DEFAULT '',
	CONSTRAINT tag_name UNIQUE (name)
);

CREATE TABLE tag_obj_assn (
	tag_id integer NOT NULL,
	obj_id integer NOT NULL,
	PRIMARY KEY (tag_id, obj_id),
	CONSTRAINT tag_obj_assn_tag_id FOREIGN KEY (tag_id) REFERENCES tag (id),
	CONSTRAINT tag_obj_assn_obj_id FOREIGN KEY (obj_id) REFERENCES obj (id)
);
CREATE INDEX tag_obj_assn_obj_id_idx ON tag_obj_assn (obj_id);

CREATE TABLE priority_type (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(100) NOT NULL,
	sort_order integer NOT NULL DEFAULT 0,
	is_default boolean NOT NULL DEFAULT false,
	CONSTRAINT priority_type_name UNIQUE (name)
);

CREATE TABLE empty_type (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(100) NOT NULL,
	CONSTRAINT empty_type_name UNIQUE (name)
);

CREATE TABLE category (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	parent_id integer NULL,
	priority_type_id integer NOT NULL,
	owner integer NULL,
	name varchar(100) NOT NULL,
	CONSTRAINT category_parent_id FOREIGN KEY (parent_id) REFERENCES category (id),
	CONSTRAINT category_priority_type_id FOREIGN KEY (priority_type_id) REFERENCES priority_type (id),
	CONSTRAINT category_owner FOREIGN KEY (owner) REFERENCES person (id)
);
CREATE INDEX category_parent_id_idx ON category (parent_id);
CREATE INDEX category_priority_type_id_idx ON category (priority_type_id);
CREATE INDEX category_owner_idx ON category (owner);

CREATE TABLE person_profile (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	person_id integer NOT NULL,
	bio text,
	website varchar(255) NULL,
	CONSTRAINT person_profile_person_id_uq UNIQUE (person_id),
	CONSTRAINT person_profile_person_id FOREIGN KEY (person_id) REFERENCES person (id)
);

CREATE TABLE person_person_assn (
	person_id integer NOT NULL,
	friend_id integer NOT NULL,
	PRIMARY KEY (person_id, friend_id),
	CONSTRAINT person_person_assn_person_id FOREIGN KEY (person_id) REFERENCES person (id),
	CONSTRAINT person_person_assn_friend_id FOREIGN KEY (friend_id) REFERENCES person (id)
);
CREATE INDEX person_person_assn_friend_id_idx ON person_person_assn (friend_id);

INSERT INTO person (id, name, email, email_verified, password) VALUES
	(1, 'Adam Kluczyk', 'klucznik@test.net', false, 'f0af0f1e34c0c5f'),
	(2, 'Maria Nowak', 'maria@test.net', true, 'c1b8e2a90d3f764'),
	(3, 'Piotr Lewandowski', 'piotr@test.net', true, '9d4e70b25ac1f83');

INSERT INTO obj (id, person_id, label, creation_date) VALUES
	(1, 1, 'First object', '2024-01-15 10:00:00'),
	(2, 2, 'Second object', '2024-02-01 14:30:00');

INSERT INTO blog_type (id, name) VALUES (1, 'Post'), (2, 'Editorial');

INSERT INTO blog_post (id, obj_id, type_id, author_id, title, body) VALUES
	(1, 1, 1, 1, 'Hello world', 'The first post.'),
	(2, 2, 2, 1, 'Draft post', 'Not published yet.');

INSERT INTO asset (id, obj_id, filename, mime_type, size) VALUES
	(1, 1, 'logo.png', 'image/png', 20480),
	(2, 1, 'manual.pdf', 'application/pdf', 512000);

INSERT INTO tag (id, name) VALUES (1, 'php'), (2, 'testing'), (3, 'orm');

INSERT INTO tag_obj_assn (tag_id, obj_id) VALUES (1, 1), (2, 1), (3, 2);

INSERT INTO priority_type (id, name, sort_order, is_default) VALUES
	(1, 'Low', 30, false), (2, 'Normal', 20, true), (3, 'Urgent', 10, false);

INSERT INTO category (id, parent_id, priority_type_id, owner, name) VALUES
	(1, NULL, 2, 1, 'Root'), (2, 1, 3, 2, 'Announcements'), (3, 1, 1, NULL, 'Archive');

INSERT INTO person_profile (id, person_id, bio, website) VALUES
	(1, 1, 'Maintainer of the framework.', 'https://example.test/adam'),
	(2, 2, 'Occasional contributor.', NULL);

INSERT INTO person_person_assn (person_id, friend_id) VALUES (1, 2), (1, 3), (2, 3);

SELECT setval(pg_get_serial_sequence('person','id'), 3);
SELECT setval(pg_get_serial_sequence('obj','id'), 2);
SELECT setval(pg_get_serial_sequence('blog_type','id'), 2);
SELECT setval(pg_get_serial_sequence('blog_post','id'), 2);
SELECT setval(pg_get_serial_sequence('asset','id'), 2);
SELECT setval(pg_get_serial_sequence('tag','id'), 3);
SELECT setval(pg_get_serial_sequence('priority_type','id'), 3);
SELECT setval(pg_get_serial_sequence('category','id'), 3);
SELECT setval(pg_get_serial_sequence('person_profile','id'), 2);
